// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixfhlxiehwntdqgtyrox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4ZmhseGllaHdudGRxZ3R5cm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTc1MjIsImV4cCI6MjA1OTgzMzUyMn0.mrOBkHacfvrpEtQrotPIN4NtYJNQbmWnjfozGg80hEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);